import Header from "./components/header"
import Footer from "./components/footer"
import { Metadata } from "next"



export const metadata: Metadata = {
  title: {
    default: "NextJs Tutorials",
    template: "%s | NextJs Tutorials",
    
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
